#*******************************************************
# Nom           : Makefile cx25.1
# Rôle          : compiler cx25.1
# Auteur        : Avrile Floro
# Version       : 1.0
# Date          : 2023-03-09
# Licence       : L1 prog_imperative
# *******************************************************
# Usage         : make
# ******************************************************

CC=gcc
CFLAGS=-Wall -std=gnu99

all: cx25.1

cx25.0: cx25.1.c
	$(CC) $(CFLAGS) cx25.1.c -o cx25.1

clean:
	rm -f cx25.0
